id: PC71394B9
initial_creation_type: input
source_metadata:
  title: Tupten Chöpel
  language: en
  description: 'Texts by the great Khenpo Tupten Chöpel (thub bstan chos ''phel, 1886–1956)
    also known as Tubga Yishyin Norbu (thub dga'' yid bzhin nor bu) of Changma hermitage
    in Dzachukha:'
  volume:
    124ad2ef7d2c4d70b4f6ec9b49696d21:
      title: Aspiration Prayer
      parent: Aspiration Prayers
created_at: '2022-03-01T02:00:07.178140'
last_modified_at: '2022-03-01T02:00:07.178146'
